version: '3'
services:
  nginx:
    image: nginx:latest
    container_name: my_nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/conf.d:/etc/nginx/conf.d
#      - ./dist:/usr/share/nginx/html
      - ./mock:/usr/share/nginx/html
    ports:
      - "80:80"
